# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/19896/EGR426_hayejord_Project3_R2/EGR426_hayejord_Project3_R2.cache/wt [current_project]
set_property parent.project_path C:/Users/19896/EGR426_hayejord_Project3_R2/EGR426_hayejord_Project3_R2.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/19896/EGR426_hayejord_Project3_R2/EGR426_hayejord_Project3_R2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/19896/EGR426_hayejord_Project3_R2/testfile.coe
read_mem C:/Users/19896/EGR426_hayejord_Project3_R2/EGR426_hayejord_Project3_R2.srcs/sources_1/new/bcd.mem
read_vhdl -library xil_defaultlib {
  C:/Users/19896/EGR426_hayejord_Project1/EGR426_hayejord_Project1.srcs/sources_1/new/Clk_1K.vhd
  C:/Users/19896/cpu/cpu.srcs/sources_1/new/alu.vhd
  C:/Users/19896/EGR426_hayejord_Project3_R2/EGR426_hayejord_Project3_R2.srcs/sources_1/new/clk_1Hz.vhd
  C:/Users/19896/cpu/cpu.srcs/sources_1/new/cpu.vhd
  C:/Users/19896/cpu/cpu.srcs/sources_1/new/microram.vhd
  C:/Users/19896/EGR426_hayejord_Project1/EGR426_hayejord_Project1.srcs/sources_1/new/mux_4to1.vhd
  C:/Users/19896/EGR426_hayejord_Project3_R2/EGR426_hayejord_Project3_R2.srcs/sources_1/new/Project3_top.vhd
}
read_ip -quiet C:/Users/19896/EGR426_hayejord_Project3_R2/EGR426_hayejord_Project3_R2.srcs/sources_1/ip/cpuram/cpuram.xci
set_property used_in_implementation false [get_files -all c:/Users/19896/EGR426_hayejord_Project3_R2/EGR426_hayejord_Project3_R2.srcs/sources_1/ip/cpuram/cpuram_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/19896/EGR426_hayejord_Project3_R2/EGR426_hayejord_Project3_R2.srcs/constrs_1/new/cpu_pins.xdc
set_property used_in_implementation false [get_files C:/Users/19896/EGR426_hayejord_Project3_R2/EGR426_hayejord_Project3_R2.srcs/constrs_1/new/cpu_pins.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Project3_top -part xc7s50csga324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Project3_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Project3_top_utilization_synth.rpt -pb Project3_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
