# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/19896/EGR426_hayejord_Project3_R2/EGR426_hayejord_Project3_R2.srcs/sources_1/ip/cpuram/cpuram.xci
# IP: The module: 'cpuram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/19896/EGR426_hayejord_Project3_R2/EGR426_hayejord_Project3_R2.srcs/sources_1/ip/cpuram/cpuram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpuram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/19896/EGR426_hayejord_Project3_R2/EGR426_hayejord_Project3_R2.srcs/sources_1/ip/cpuram/cpuram.xci
# IP: The module: 'cpuram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/19896/EGR426_hayejord_Project3_R2/EGR426_hayejord_Project3_R2.srcs/sources_1/ip/cpuram/cpuram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpuram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
