@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Wed Apr 20 01:46:34 -0400 2022
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 4fa88f189af24056ae6634de38b531c9 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip -L xpm --snapshot cputb1_behav xil_defaultlib.cputb1 -log elaborate.log"
call xelab  -wto 4fa88f189af24056ae6634de38b531c9 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip -L xpm --snapshot cputb1_behav xil_defaultlib.cputb1 -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
