set_property PACKAGE_PIN F14 [get_ports mclk]
set_property IOSTANDARD LVCMOS33 [get_ports mclk]

# BTN0
set_property PACKAGE_PIN J2 [get_ports reset]  
set_property IOSTANDARD LVCMOS33 [get_ports reset]

# LEDS
set_property PACKAGE_PIN A4 [get_ports {Outport1[7]}]
set_property PACKAGE_PIN B4 [get_ports {Outport1[6]}]
set_property PACKAGE_PIN A3 [get_ports {Outport1[5]}]
set_property PACKAGE_PIN B3 [get_ports {Outport1[4]}]
set_property PACKAGE_PIN A2 [get_ports {Outport1[3]}]
set_property PACKAGE_PIN B2 [get_ports {Outport1[2]}]
set_property PACKAGE_PIN C3 [get_ports {Outport1[1]}]
set_property PACKAGE_PIN E6 [get_ports {Outport1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport1[0]}]

set_property PACKAGE_PIN E5 [get_ports {Outport0[7]}]
set_property PACKAGE_PIN E3 [get_ports {Outport0[6]}]
set_property PACKAGE_PIN E2 [get_ports {Outport0[5]}]
set_property PACKAGE_PIN E1 [get_ports {Outport0[4]}]
set_property PACKAGE_PIN F2 [get_ports {Outport0[3]}]
set_property PACKAGE_PIN F1 [get_ports {Outport0[2]}]
set_property PACKAGE_PIN G2 [get_ports {Outport0[1]}]
set_property PACKAGE_PIN G1 [get_ports {Outport0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport0[0]}]

# SWITCHES
set_property PACKAGE_PIN K1 [get_ports {Inport1[7]}]
set_property PACKAGE_PIN K2 [get_ports {Inport1[6]}]
set_property PACKAGE_PIN L1 [get_ports {Inport1[5]}]
set_property PACKAGE_PIN M1 [get_ports {Inport1[4]}]
set_property PACKAGE_PIN M2 [get_ports {Inport1[3]}]
set_property PACKAGE_PIN N1 [get_ports {Inport1[2]}]
set_property PACKAGE_PIN N2 [get_ports {Inport1[1]}]
set_property PACKAGE_PIN P1 [get_ports {Inport1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport1[0]}]

set_property PACKAGE_PIN P2 [get_ports {Inport0[7]}]
set_property PACKAGE_PIN R1 [get_ports {Inport0[6]}]
set_property PACKAGE_PIN R2 [get_ports {Inport0[5]}]
set_property PACKAGE_PIN T1 [get_ports {Inport0[4]}]
set_property PACKAGE_PIN T2 [get_ports {Inport0[3]}]
set_property PACKAGE_PIN U1 [get_ports {Inport0[2]}]
set_property PACKAGE_PIN U2 [get_ports {Inport0[1]}]
set_property PACKAGE_PIN V2 [get_ports {Inport0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport0[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {left_Anode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_Anode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_Anode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_Anode[0]}]
set_property PACKAGE_PIN A8 [get_ports {left_Anode[3]}]
set_property PACKAGE_PIN C7 [get_ports {left_Anode[2]}]
set_property PACKAGE_PIN C4 [get_ports {left_Anode[1]}]
set_property PACKAGE_PIN D5 [get_ports {left_Anode[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {right_Anode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_Anode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_Anode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_Anode[0]}]
set_property PACKAGE_PIN E4 [get_ports {right_Anode[3]}]
set_property PACKAGE_PIN F3 [get_ports {right_Anode[2]}]
set_property PACKAGE_PIN J4 [get_ports {right_Anode[1]}]
set_property PACKAGE_PIN H3 [get_ports {right_Anode[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {right_Segs[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_Segs[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_Segs[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_Segs[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_Segs[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_Segs[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_Segs[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_Segs[0]}]
set_property PACKAGE_PIN C1 [get_ports {right_Segs[7]}]
set_property PACKAGE_PIN D1 [get_ports {right_Segs[6]}]
set_property PACKAGE_PIN H4 [get_ports {right_Segs[5]}]
set_property PACKAGE_PIN B1 [get_ports {right_Segs[4]}]
set_property PACKAGE_PIN C2 [get_ports {right_Segs[3]}]
set_property PACKAGE_PIN D2 [get_ports {right_Segs[2]}]
set_property PACKAGE_PIN J3 [get_ports {right_Segs[1]}]
set_property PACKAGE_PIN F4 [get_ports {right_Segs[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {left_Segs[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_Segs[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_Segs[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_Segs[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_Segs[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_Segs[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_Segs[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_Segs[0]}]
set_property PACKAGE_PIN A6 [get_ports {left_Segs[7]}]
set_property PACKAGE_PIN B5 [get_ports {left_Segs[6]}]
set_property PACKAGE_PIN D6 [get_ports {left_Segs[5]}]
set_property PACKAGE_PIN A7 [get_ports {left_Segs[4]}]
set_property PACKAGE_PIN B7 [get_ports {left_Segs[3]}]
set_property PACKAGE_PIN A5 [get_ports {left_Segs[2]}]
set_property PACKAGE_PIN C5 [get_ports {left_Segs[1]}]
set_property PACKAGE_PIN D7 [get_ports {left_Segs[0]}]

